/* rangesearch_impala_interface.h : Impala interface file generated by impala */
#ifndef RANGESEARCH_IMPALA_INTERFACE_H
#define RANGESEARCH_IMPALA_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif

struct QueryResult {
    int size;
    int capacity;
    unsigned long long* pointers;
};

struct Float3 {
    float x;
    float y;
    float z;
};

struct HashGridInfo {
    float radius;
    float radius_sqr;
    float cell_size;
    float inv_cell_size;
    int indices_size;
    int cell_ends_size;
    struct Float3 bbox_min;
    struct Float3 bbox_max;
    unsigned long long* indices;
    int* cell_ends;
};

void hashgrid_query(struct QueryResult* output, struct HashGridInfo* info, struct Float3 query_pos);

#ifdef __cplusplus
}
#endif

#endif /* RANGESEARCH_IMPALA_INTERFACE_H */

